GET http://localhost:3000/user-api/getallusers

###
POST http://localhost:3000/user-api/login
Content-Type: application/json

{
    "username" : "rohan",
    "password" : "rohan"
}

###
POST http://localhost:3000/user-api/createuser
Content-Type: application/json

{
    "username" : "rohan",
    "password" : "rohan",
    "age" : 22,
    "email" : "rohanjoshi@gmail.com"
}

###
PUT http://localhost:3000/user-api/updateuser
Content-Type: application/json

{
    "username" : "rohan",
    "password" : "rohan",
    "age" : 23,
    "email" : "rohan123joshi@gmail.com"
}

###
DELETE  http://localhost:3000/user-api/deleteuser/rohan



###
GET http://localhost:3000/product-api/getallproducts

###
GET http://localhost:3000/product-api/getproduct/200

###
POST http://localhost:3000/product-api/createproduct 
Content-Type: application/json

{
    "productId" : 200,
    "product" : "Music System",
    "brand" : "Sony",
    "price" : "100000"
}

###
PUT http://localhost:3000/product-api/updateproduct 
Content-Type: application/json

{
    "productId" : 200,
    "product" : "Music System",
    "brand" : "Sony",
    "price" : "150000"
}

###
DELETE http://localhost:3000/product-api/deleteproduct/200 

